apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Namespace
  - namespace.yaml

  # API
  - svc-api.yaml
  - deploy-api.yaml

  # Frontend
  - svc-frontend.yaml
  - deploy-frontend.yaml

  # Network Policies (keep only these three)
  - netpol-default-deny.yaml
  - netpol-allow-frontend-to-api.yaml
  - netpol-allow-api-egress.yaml
