apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: finapp
spec:
  type: ClusterIP
  selector:
    app: api
  ports:
    - name: http
      port: 80
      targetPort: 5000   # <-- was 8080
